### ISSUE TITLE
edited : the Pendant isn't working (under some conditions).

### ISSUE THREAD

**Issue by NewMilenium** [hm-ysjiang/PotionCapsule#2] opened 2019-09-04 16:52 UTC
(gratz' for the solved bug last time)

When i use the Capsule Pendant, 
1) the items of my hotbar line are visually cloned to the bottom inventory line (not exactly in the same order though),
2) the items or my "normal" bottom line and of my middle line are put to the middle line and upper line, 
3) the items of my "normal" upper line seems to be put inside the Capsule Pendant (further tests : seems it's only visual, the items are not really inside). 
Closing the Pendant doesn't solve it.
Clicking an item "updates" the inventory and solves all those visual effects.

**Information :**
 - Mod Version: PotionCapsule-1.0.3
 - Forge Version: 1.14.4-forge-28.0.49
 - Crash Log: no crash

**Additional context**
Mods installed : 
branders-enhanced-mob-spawners.v1.4.2-1.14.4, 
buildinggadgets-3.0.4, 
ChunkNoGoByeBye-1.14.4-1.0.2, 
craftingstation-2.0.2a, 
curios-FORGE-1.14.4-0.23, 
EnderBags-1.14.4-4.1.2, 
exp_bottling-1.14.4-3, 
ForgivingVoid_1.14.2-3.0.5, 
gates-1.2.0 <-- not functional anymore, not working since the moment i put your mod, 
gravestone-1.15.0, 
jei-1.14.4-6.0.0.10, 
Mine+and+Slash-1.14.4-2.5.2, 
Placebo-1.14.4-2.1.11, 
PotionCapsule-1.0.3, 
spiketraps-1.0, 
Xaeros_Minimap_1.17.6_Forge_1.14.4

**Screenshots**
If the upload doesn't work, i also uploaded the image here : https://ibb.co/9hZ4xtS

![minecraft_capsule bug 2](https://user-images.githubusercontent.com/2199445/64274915-b43af800-cf44-11e9-8661-1f7309c21ee0.PNG)

Explaining the image :
1.1 : my inventory
1.2 : opening the pendant
1.3 : just closed the pendant

2.1 : my inventory but this time i got items on the upper inventory line
2.2 : opening the pendant
2.3 : dragging the 4 redstone that seemed to be IN the pendant
2.4 : i've dropped on the floor the 4 redstone and the 6 capsules. Then just closed the pendant.

**Comment by hm-ysjiang** [comment] 2019-09-04 21:39
Hump, I had encountered this problem before when I was in the dev environment, but I am pretty sure that I got that fixed then.

I will check it again later, and thanks for the report.

**Comment by hm-ysjiang** [comment] 2019-09-05 04:46
BTW, what does it mean that the mod (gates) is not functional?

**Comment by NewMilenium** [comment] 2019-09-05 07:13
Right after putting your mod, when i started loading my world, forge stopped the world loading and printed things like "entry missing : gates", and this for each gate, "xor gate", "and gate", etc, and i had the choice to keep loading the world and lose the gates or stop loading. I stopped at first, checked my mods, relaunched minecraft, but the same thing happened. Since i had only a few xor gates in the world, i decided to drop them and test your mod.
In-game, there is no gate anymore, nor craftable, nor in jei, nor in the world. Like the mod isn't loaded anymore.

**Comment by hm-ysjiang** [comment] 2019-09-05 07:54
I cannot reproduce this bug with forge 28.0.49 with only PotionCapsule 1.0.3...
Even with gates1.2.0, the game works fine.

Can you provide your latest.log file so i can take a look at what happened?
I will also try to do the old binary check method to see if this is a mod incompatible issue.

**Comment by NewMilenium** [comment] 2019-09-05 08:34
Yes, but there are several types of logs, please tell me which one you want and its approximate path so i won't provide you a useless log.
Also, the issue is worse than i thought : even with an empty inventory except the pendant and a stack of filled capsules, i can't put any capsule in the pendant - i tried several ways. I put the capsules "only visually" in the pendant, the pendant is actually empty when checking, the capsules are still in my inventory.

**Comment by NewMilenium** [comment] 2019-09-05 08:42
[latest.log](https://github.com/hm-ysjiang/PotionCapsule/files/3578279/latest.log)

Sorry, i read badly "latest.log", here it is. 
Though i can't find any line produced at the moment i was interacting with the pendant. I hope you'll find something else in the other lines.

**Comment by hm-ysjiang** [comment] 2019-09-06 08:31
I can reproduce the issue with your mods setup, I tried to remove the mods one by one, and the registry missing problem stopped after I removed ForgivingVoid_1.14.2-3.0.5.
Then I replaced it with ForgivingVoid_1.14.4-3.0.6, everything seems to behave now.

EDIT:
Oh btw, I think forge will automatically backup your world if you load a save with some missing entry. You can try to restore your world using the backup.

**Comment by NewMilenium** [comment] 2019-09-06 12:07
Hello,

it seems so far that, by replacing ForgivingVoid version 3.0.5 by the version 3.0.6, that the issue of the gates mod not working is solved.
However, i still have the same gameplay issue with the Pendant.

Should i simply try to use a more recent version of forge, maybe?

**Comment by hm-ysjiang** [comment] 2019-09-06 13:25
The pendant is working on my side and I am using the same forge version to test...

I think the issue is because the inventory slot id is mismapped while creating the gui container.
Are the Gelatin Extractor and Former behaving? They are using the same code to map the inventory slots. 

And does this happen in every single world save? I think there is a possibility that some mod's progress might mess with the player inventory. Would you mind creating a new world and check if the issue exists inside the new world?

**Comment by NewMilenium** [comment] 2019-09-06 14:25
I created a new world with exactly the same forge and mods,
mode survival, 
(i start with some items that come from Mine & Slash)
opened to lan, cheats on, 
given myself some capsules (about 30), a potion of strength II and a potion of slow falling,
filled some capsules with these,
put the capsule in the Pendant (strength II ones in attacking, slow falling in falling) (<-- no problem here, already a big change),
tested falling and attacking : works perfectly.
Then mixed both capsules together, put in the keybinded trigger : works perfectly.

You seem to be, again, perfectly right.
If i can help, test, do anything more, just ask. (i don't know what to conclude nor do about "the inventory slot id is mismapped while creating the gui container")

Absolutely no problem seen with the Gelatin Extractor nor the Former. I created the wart dust, the gelatin and the capsules as a survival player is supposed to in my (first) world.

**Comment by hm-ysjiang** [comment] 2019-09-06 15:00
So the extractor and the former is working in your original world?

Could you send your original world save to me so I can investigate further?

**Comment by NewMilenium** [comment] 2019-09-06 16:18
Ok, uploading. Prepare to use 7zip to uncompress it.

**Comment by NewMilenium** [comment] 2019-09-06 16:56
Yes, the name of my world is "andagaaain" .
Here you go :
https://filebin.net/vhqdhwt0yxm6455l/andagaaain.7z?t=d2gzi0vz

**Comment by hm-ysjiang** [comment] 2019-09-06 18:24
Oh, that is my fault. I forgot to set the active hand.
Should be fixed in the next build (1.0.4).

**Closed as completed** 2019-09-06 18:42 UTC
Labels: bug, more info needed, resolved

**Comment by hm-ysjiang** [comment] 2019-09-06 18:50
Ok, update 1.0.4 on CurseForge.
Basically, the issue is that pendant will not work properly if the player is using both hands. Version 1.0.4 should fix this.
