### ISSUE TITLE
(really sorry! again...) All capsules disappeared of the Pendant

### ISSUE THREAD

**Issue by NewMilenium** [hm-ysjiang/PotionCapsule#4] opened 2019-09-06 20:01 UTC
Sorry for this bug report and thank you for your work.

I downloaded your last version (PotionCapsule-1.0.4), it all seemed to work fine. I started putting various capsules :
 - a stack of 128 capsules (in 2 stacks of 64 i combined in the Pendant, of course) of fire resistance in the "in fire" trigger,
 - some (dunno, around 64 or 90) capsules of slow falling in the "when falling" trigger,
Then i started combining capsules in my inventory (12 capsules of strength II + 12 capsules of jump boost II + 12 capsules of regeneration II + 12 capsules of speed II), it worked fine, 
then i used the pendant to put those 12 resulting capsules inside... the pendant is empty!

I tried falling, just in case it was only visual... no, no potion effect. Pendant still empty.
I put fire on the ground, walk in... no fire resistance either. Pendant still empty.

I saw something you've written somewhere that came to my mind later : you've written we shouldn't have anything in the second hand when using the Pendant? Or what was it..? 
Sorry, when i used the pendant, i had my "Thundering Torch of Rock Skin" (item of Mine & Slash) in my second hand. I tried playing around with an empty second hand, re-putting the Torch, no change.

Should it be put in your main post maybe? Or i was too fast downloading the new version and you are working on the main post? Sorry again for this 4th bug report.

Maybe it's a "once-only" bug, and i can use that pendant now, it won't empty itself again? I'll play around and post more information if i gather some.

**Information :**
 - Mod Version: PotionCapsule-1.0.4
 - Forge Version: 1.14.4-forge-28.0.49

**Mods used : **
branders-enhanced-mob-spawners.v1.4.2-1.14.4,
buildinggadgets-3.0.4,
ChunkNoGoByeBye-1.14.4-1.0.2,
craftingstation-2.0.2a,
curios-FORGE-1.14.4-0.23,
EnderBags-1.14.4-4.1.2,
exp_bottling-1.14.4-3,
ForgivingVoid_1.14.4-3.0.6,
gates-1.2.0,
gravestone-1.15.0,
jei-1.14.4-6.0.0.10,
Mine+and+Slash-1.14.4-2.5.2,
Placebo-1.14.4-2.1.11,
PotionCapsule-1.0.4,
spiketraps-1.0,
Xaeros_Minimap_1.17.6_Forge_1.14.4

**Comment by NewMilenium** [comment] 2019-09-06 20:19
I kept putting capsules in the pendant.
It worked (putting them, using the pendant, while empty handed, while holding my torch, tried falling, it worked)...
... and a bit later, the capsules of the "when on fire" trigger are all gone, and the others still here.

**Comment by hm-ysjiang** [comment] 2019-09-07 10:54
The mod is still in beta , so bug reports are good.
The both hand thing is that the previos bug was only appearing when the player is messing around with their both hands, dont mind it since that was fixed.

Only the onFire trigger is emptied? or the whole pendant? 
Does this only happens occasionally? Is there a way to reproduce it?

**Comment by NewMilenium** [comment] 2019-09-07 22:04
(Both disappearances happened on my world "andagaaain" posted in a previous solved issue  ---> )

At the first disappearance, (as i've written in my first post) they all disappeared (when falling, onFire).
At the second disappearance, (as i've written in my second post) only the onFire trigger was emptied (the capsules in when falling and the ones in when using the keybind were still inside).

I don't know for now it it happens occasionally, or if i can reproduce it more than these 2 different observations. When i have more information, i'll post again of course.

**Comment by hm-ysjiang** [comment] 2020-01-04 08:18
^ Closing this temporarily
Re-open this if new info is observed.

**Closed as completed by hm-ysjiang** 2020-01-04 08:18 UTC
Labels: more info needed
